anno=int(input("INGRESE EL AÑO DE NACIMIENTO: "))
edad=2025-anno
print("SU EDAD ES:",edad)
if edad<=11:
    print("ES INFANTE")
    if edad<=5:
        print("DE PRIMERA INFANCIA, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
    else:
        print("DE SEGUNDA INFANCIA, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
elif edad<=14:
    print("ES ADOLESCENTE, ES JOVEN, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
elif edad<=18:
    print("ES ADOLESCENTE, ES JOVEN, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
elif edad<=26:
    print("ES JOVEN, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
elif edad<=59:
    print("ES ADULTO, DE ADULTEZ JOVEN/MEDIA, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
elif edad<=90:
    print("DE VEJEZ")
    if edad<=74:
        print("ES ADULTO MAYOR, ANCIANO JOVEN, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
    elif edad<=80:
        print("ES ANCIANO, LE QUEDAN",80-edad,"AÑOS DE VIDA SEGÚN EL PROMEDIO DE ESPERANZA DE VIDA")
    else:
        print("ES ANCIANO, HA PASADO LA ESPERANZA DE VIDA EN",edad-80,"AÑOS")
else:
    print("DE VEJEZ, ES ANCIANO LONGEVO, HA PASADO LA ESPERANZA DE VIDA EN",edad-80,"AÑOS")
